triggers:
- envs: []
  last_enabled_at: 2024-02-11 09:49:45.793126
  name: green_taxi_etl_daily_sched
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-11 05:00:00
  status: active
  variables: {}
